from django.contrib import admin
from .models import Food, Accessories, Art, Backgrounds, Beauty, Business, Celebrate, Children, Cinema, City, Communication, Education, Fashion, Fitness, Flowers, Health, Holidays, Home, Jewlery, Landscape, Love, Money, Nature, People, Recreation, Retail, Seasons, Spring, Technology, Transportation, Travel, Urbanlife, Wellness, Work, World
# Register your models here.

admin.site.register(Food,)
admin.site.register(Accessories,)
admin.site.register(Art,)
admin.site.register(Backgrounds,)
admin.site.register(Beauty,)
admin.site.register(Business,)
admin.site.register(Celebrate,)
admin.site.register(Children,)
admin.site.register(Cinema,)
admin.site.register(City,)
admin.site.register(Communication,)
admin.site.register(Education,)
admin.site.register(Fashion,)
admin.site.register(Fitness,)
admin.site.register(Flowers,)
admin.site.register(Health,)
admin.site.register(Holidays,)
admin.site.register(Home,)
admin.site.register(Jewlery,)
admin.site.register(Landscape,)
admin.site.register(Love,)
admin.site.register(Money,)
admin.site.register(Nature,)
admin.site.register(People,)
admin.site.register(Recreation,)
admin.site.register(Retail,)
admin.site.register(Seasons,)
admin.site.register(Spring,)
admin.site.register(Technology,)
admin.site.register(Transportation,)
admin.site.register(Travel,)
admin.site.register(Urbanlife,)
admin.site.register(Wellness,)
admin.site.register(Work,)
admin.site.register(World,)
