from django.urls import path
from . import views

urlpatterns = [
    path('', views.catlog_home, name="catlog_home"),
    path('food/', views.food, name="food"),
    path('accessories/', views.accessories, name="accessories"),
    path('art/', views.art, name="art"),
    path('backgrounds/', views.backgrounds, name="backgrounds"),
    path('beauty/', views.beauty, name="beauty"),
    path('business/', views.business, name="business"),
    path('celebrate/', views.celebrate, name="celebrate"),
    path('children/', views.children, name="children"),
    path('cinema/', views.cinema, name="cinema"),
    path('city/', views.city, name="city"),
    path('communication/', views.communication, name="communication"),
    path('education/', views.education, name="education"),
    path('fashion/', views.fashion, name="fashion"),
    path('fitness/', views.fitness, name="fitness"),
    path('flowers/', views.flowers, name="flowers"),
    path('health/', views.health, name="health"),
    path('holidays/', views.holidays, name="holidays"),
    path('home/', views.home, name="home_cat"),
    path('jewlery/', views.jewlery, name="jewlery"),
    path('landscape/', views.landscape, name="landscape"),
    path('love/', views.love, name="love"),
    path('money/', views.money, name="money"),
    path('nature/', views.nature, name="nature"),
    path('people/', views.people, name="people"),
    path('recreation/', views.recreation, name="recreation"),
    path('retail/', views.retail, name="retail"),
    path('seasons/', views.seasons, name="seasons"),
    path('spring/', views.spring, name="spring"),
    path('technology/', views.technology, name="technology"),
    path('transportation/', views.transportation, name="transportation"),
    path('travel/', views.travel, name="travel"),
    path('urbanlife/', views.urbanlife, name="urbanlife"),
    path('wellness/', views.wellness, name="wellness"),
    path('work/', views.work, name="work"),
    path('world/', views.world, name="world"),
]
