# Generated by Django 2.1.5 on 2019-01-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0002_accessories_art_backgrounds_beauty_business_celebrate_children_cinema_city_communication_education_f'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jewelry',
            new_name='Jewlery',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='accessories_1',
            new_name='health_1',
        ),
        migrations.RenameField(
            model_name='jewlery',
            old_name='jewlry_1',
            new_name='jewlery_1',
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='transportaion_1',
            new_name='transportation_1',
        ),
    ]
