# Generated by Django 2.1.5 on 2019-01-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0003_auto_20190114_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catlog_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catlog_1', models.TextField(default='', max_length=300)),
            ],
        ),
    ]
