# Generated by Django 2.1.5 on 2019-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_1',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
