# Generated by Django 2.1.5 on 2019-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190111_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='High_resolve_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_resolve_urls', models.TextField(default='', max_length=300)),
            ],
        ),
    ]
